import { ArrowRight, Building2, CheckCircle2, ChevronRight, Download, Factory, Globe2, Mail, MapPinned, MessageCircle, RadioTower, Satellite, ShieldCheck, Wrench } from "lucide-react";
import SiteHeader from "./components/SiteHeader";

const products = [
  ["GNSS Receiver", "High-performance RTK devices for surveying, mapping and construction workflows.", "/products/gnss-receivers"],
  ["Rugged & GIS", "Portable high-precision terminals and controllers for field data collection.", "/products/rugged-gis"],
  ["GNSS Antenna", "Choke ring, survey and helix antennas for stable positioning accuracy.", "/products/gnss-antennas"],
  ["Precision Agriculture", "Auto-steering and land leveling systems for modern farm operations.", "/products/precision-agriculture-machine-control"],
  ["Machine Control", "Dozer and excavator guidance systems powered by high-precision GNSS.", "/products/precision-agriculture-machine-control"],
  ["VRS Solution", "CORS/VRS services and base station networks for centimeter-level corrections.", "/products/gnss-application-solutions"]
];

const advantages = [
  ["OEM/ODM", "Custom product and solution support for distributors and brand partners."],
  ["15+ Years R&D", "Founded by engineers with long-term GNSS and RTK development background."],
  ["60%+ Engineers", "A technical team structure built for product iteration and project support."],
  ["Global Project Support", "Serving surveying, monitoring, agriculture and construction customers worldwide."]
];

const applications = ["Surveying & Mapping", "Construction Monitoring", "CORS / VRS Networks", "Precision Agriculture", "Machine Control", "GIS Data Collection", "Marine & USV", "Deformation Monitoring"];

const faqs = [
  ["Can TOKNAV support OEM or ODM projects?", "Yes. TOKNAV supports OEM/ODM cooperation for GNSS receivers, RTK systems and related positioning solutions."],
  ["Which markets are suitable for TOKNAV products?", "The website plan focuses on global B2B buyers, especially importers, distributors, contractors and EPC companies in markets such as UAE, Saudi Arabia, Nigeria and South Africa."],
  ["What should buyers include in an inquiry?", "Please share your country, buyer type, target application, product category, estimated quantity and WhatsApp or email contact."]
];

function SectionTitle({ title, text, titleKey, textKey }: { title: string; text: string; titleKey?: string; textKey?: string }) {
  return <div className="section-title"><h2 data-i18n={titleKey}>{title}</h2><p data-i18n={textKey}>{text}</p></div>;
}

export default function Home() {
  return <main>
    <SiteHeader />
    <section className="hero"><div className="hero-copy"><h1 data-i18n="home.hero.title">High-Precision GNSS Receivers & RTK Solutions Manufacturer</h1><p data-i18n="home.hero.subtitle">OEM/ODM GNSS receivers, antennas, CORS/VRS systems and machine control solutions for global distributors, contractors and system integrators.</p><div className="hero-actions"><a className="primary-button" href="#contact"><span data-i18n="cta.getQuote">Get a Quote</span> <ArrowRight size={18} /></a><a className="secondary-button" href="#products"><span data-i18n="cta.exploreProducts">Explore Products</span> <ChevronRight size={18} /></a></div><div className="hero-proof">{advantages.map(([label]) => <span key={label}>{label}</span>)}</div></div><div className="hero-visual" aria-label="GNSS receiver product preview"><div className="receiver-shell"><div className="receiver-top" /><div className="receiver-body"><span>TOKNAV</span><div className="receiver-screen" /></div></div><div className="signal-ring ring-one" /><div className="signal-ring ring-two" /><div className="hero-panel"><Satellite size={20} /><span>Full-system, multi-frequency RTK positioning</span></div></div></section>
    <section className="metric-band"><div><strong>2019</strong><span>Founded by R&D engineers</span></div><div><strong>2,500m²</strong><span>Office and factory footprint from catalog</span></div><div><strong>100+</strong><span>Countries and regions served in latest brochures</span></div><div><strong>CE / FCC / KC</strong><span>Certification signals listed in product materials</span></div></section>
    <section className="products section" id="products"><SectionTitle title="Product Lines Built for Field Accuracy" text="Organize the site around buyer search intent: receivers, antennas, rugged terminals and complete positioning solutions." titleKey="home.products.title" textKey="home.products.text" /><div className="product-grid">{products.map(([name, text, href], index) => <a className="product-card" href={href} key={name}><span>{String(index + 1).padStart(2, "0")}</span><h3>{name}</h3><p>{text}</p><ChevronRight size={18} /></a>)}</div></section>
    <section className="split-section section" id="oem"><div><SectionTitle title="Why Overseas Buyers Choose TOKNAV" text="The homepage should make manufacturing capability, technical support and distributor cooperation clear before buyers ask for price." titleKey="home.oem.title" textKey="home.oem.text" /><div className="advantage-list">{advantages.map(([label, text]) => <div className="advantage-item" key={label}><CheckCircle2 size={22} /><div><h3>{label}</h3><p>{text}</p></div></div>)}</div></div><div className="capability-panel"><Factory size={34} /><h3>Source manufacturer and solution partner</h3><p>Position the website for higher-quality inquiries: distributors, system integrators, contractors and OEM brand partners.</p><ul><li>GNSS RTK receiver series</li><li>CORS/VRS and deformation monitoring</li><li>Precision agriculture and machine control</li><li>Catalog download and quotation workflow</li></ul></div></section>
    <section className="solutions section" id="solutions"><SectionTitle title="Application Pages for SEO and Paid Traffic" text="Each application page should explain the problem, recommended product mix, deployment workflow and inquiry path." titleKey="home.solutions.title" textKey="home.solutions.text" /><div className="solution-layout"><div className="solution-map"><RadioTower className="tower-icon" size={64} /><div className="map-line line-a" /><div className="map-line line-b" /><div className="map-node node-a">Base</div><div className="map-node node-b">Rover</div><div className="map-node node-c">Cloud</div></div><div className="application-list">{applications.map((item) => <div key={item}><MapPinned size={18} /><span>{item}</span></div>)}</div></div></section>
    <section className="trust section" id="about"><div className="trust-copy"><SectionTitle title="Real Trust Assets, Not Empty Claims" text="Use Jeffrey, customer visits, field testing and project photos to make the website feel like a real export business with technical people behind it." titleKey="home.trust.title" textKey="home.trust.text" /><div className="advisor"><div className="advisor-photo">J</div><div><h3>Jeffrey · GNSS Project Contact</h3><p>A named contact gives buyers a clearer path for pricing, distributor cooperation and project discussion.</p></div></div></div><div className="trust-grid"><div><Building2 size={28} /><strong>Company strength</strong><span>R&D-led team, factory footprint and product catalog depth.</span></div><div><ShieldCheck size={28} /><strong>Quality signals</strong><span>Only show verified certifications and field proof.</span></div><div><Globe2 size={28} /><strong>Global markets</strong><span>Built for UAE, Saudi Arabia, Nigeria, South Africa and beyond.</span></div><div><Wrench size={28} /><strong>Solution support</strong><span>Hardware, software, training and project configuration.</span></div></div></section>
    <section className="inquiry section" id="contact"><div><SectionTitle title="Turn Traffic Into Qualified Inquiries" text="The form asks for the fields that matter for sales follow-up without making first contact too heavy." titleKey="home.inquiry.title" textKey="home.inquiry.text" /><div className="contact-actions"><a href="mailto:info@toknavgnss.com"><Mail size={18} />info@toknavgnss.com</a><a href="#"><MessageCircle size={18} />WhatsApp Consultation</a><a href="/contact"><MapPinned size={18} />View Location</a><a href="#"><Download size={18} />Download Catalog</a></div><div className="location-card"><div><MapPinned size={22} /><strong data-i18n="home.location.title">Guangzhou Office</strong><span data-i18n="home.location.address">No. 9 Caipin Road, Huangpu District, Guangzhou, Guangdong, China</span></div><a href="/contact"><span data-i18n="home.location.map">Open company map</span> <ArrowRight size={16} /></a></div><div className="faq-list">{faqs.map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div><form className="quote-form"><label><span data-i18n="form.name">Name</span><input placeholder="Your name" data-i18n-placeholder="form.placeholder.name" /></label><label><span data-i18n="form.email">Email</span><input placeholder="name@company.com" data-i18n-placeholder="form.placeholder.email" type="email" /></label><label><span data-i18n="form.country">Country</span><input placeholder="UAE, Saudi Arabia, Nigeria..." data-i18n-placeholder="form.placeholder.country" /></label><label><span data-i18n="form.product">Product Requirement</span><select defaultValue=""><option value="" disabled>Select a category</option><option>GNSS Receiver</option><option>GNSS Antenna</option><option>CORS / VRS Solution</option><option>Precision Agriculture</option><option>Machine Control</option><option>OEM / ODM Project</option></select></label><label><span data-i18n="form.message">Message</span><textarea placeholder="Tell us your application, quantity and timeline." data-i18n-placeholder="form.placeholder.message" /></label><button type="button"><span data-i18n="form.submit">Submit Inquiry</span> <ArrowRight size={18} /></button></form></section>
    <footer><strong>TOKNAV</strong><span>Guangzhou Toksurvey Information Technology Co., Ltd.</span><span>No. 9 Caipin Road, Huangpu District, Guangzhou, China</span><span data-i18n="footer.tagline">GNSS Receiver Manufacturer · Professional OEM & ODM</span></footer>
  </main>;
}
